# Common parameters
debug_level: 0

# Scan over all combinations of specified parameter values
parameter_scan:

  # pthat bins are required, and should come first
  pt_hat_bins:
    label: 'pt_hat_bins'
    values: [1, 2, 3, 4, 5, 7, 9, 11, 13, 15, 17, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 350, 400, 450, 500, 550, 600, 700, 800, 900, 1000, 1100, 1200, 1300]

  # additional parameters are optional
  parameter1:
    label: 'eCM'
    values: [2760, 5020]
    
  parameter2:
    label: 'weak_decays'
    values: ['on', 'off']

# Generation
xml_user_file: '/home/jetscape-user/JETSCAPE/config/jetscape_user_PP19.xml'
xml_master_file: '/home/jetscape-user/JETSCAPE/config/jetscape_main.xml'

# Analysis parameters -- required
n_event_max: 10000
reader: hepmc
progress_bar: True
scale_histograms: True
merge_histograms: False

# Analysis parameters -- user-defined
min_track_pt: 0.01       # Used for both hadron/parton and jet histograms
abs_track_eta_max: 1.0   # Used only for hadron/parton histograms -- jet finding uses all hadrons as constituents
jetR: [0.2, 0.4]
min_jet_pt: 20.
abs_jet_eta_max: [0.3, 2.0, 2.8]
