# Common parameters
debug_level: 0

# Scan over all combinations of specified parameter values
parameter_scan:

  # pthat bins are required, and should come first
  pt_hat_bins:
    label: 'pt_hat_bins'
    #values: [1, 2, 3, 4, 5, 7, 9, 11, 13, 15, 17, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 350, 400, 450, 500, 550, 600, 700, 800, 900, 1000, 1100, 1200, 1300]
    values: [55, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]

  # additional parameters are optional
  parameter1:
    label: 'eCM'
    values: [5020]

# Generation
xml_user_file: '/home/jetscape-user/JETSCAPE/config/jetscape_user_PP_photon_jet.xml'
xml_master_file: '/home/jetscape-user/JETSCAPE/config/jetscape_main.xml'

# Analysis parameters -- required
n_event_max: 1000
reader: ascii
progress_bar: True
scale_histograms: True
merge_histograms: True

# Analysis parameters -- user-defined
min_track_pt: 0.01       # Used for both hadron/parton and jet histograms
abs_track_eta_max: 1.0   # Used only for hadron/parton histograms -- jet finding uses all hadrons as constituents
jetR: [0.4]
# ATLAS PLB 789 (2019) 167-190
# eta_max for jet finding hadrons not implemented yet
min_jet_pt: 31.6
jet_eta_cut: 2.8
azimuthal_separation: 2.74889 # 7pi/8
min_prompt_photon_pt: 63.1
max_prompt_photon_pt: 200.
prompt_photon_eta_cut: 2.37
prompt_photon_pt_ranges: # pT ranges with measurements reported
  - [63.1, 79.6]
  - [79.6, 100]
  - [100, 158]
  - [158, 200]

